{{- $namespace := .Values.namespace }}
{{- $env := .Values.env }}
{{- $appName := .Values.appName | default "sr-algo" }}
{{- $server_name := .Values.deployment_server.name | default "sr-algo"}}
{{- with .Values.network }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .name }}-{{ $env }}"
  namespace: {{ $namespace }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port:  {{ .port }}
      targetPort: {{ .targetPort }}
  selector:
    deploymentconfig: "{{ $server_name }}-{{ $env }}"

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .name }}-{{ $env }}"
  namespace: {{ $namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: "/"
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - {{ .hostName }}
     secretName: sr-algo-azure-tls
  rules:
  - host: {{ .hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .name }}-{{ $env }}"
            port:
              number: {{ .port }}
   
---
{{- end }}
